version: '3.8'

services:
  app:
    build: .
    # Mapeamos nuestra carpeta actual al directorio /app del contenedor
    volumes:
      - .:/app
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis

  redis:
    image: redis:alpine
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes

volumes:
  redis-data:
